package com.example.springbatchexample.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.Accessors;

/**
 * Database Table Remarks:
 *   従業員
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms.employee
 */
@Data
@Accessors
@EqualsAndHashCode
@Builder
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class Employee implements Serializable {
    /**
     * Database Column Remarks:
     *   内部ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.created_date
     *
     * @mbg.generated
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.last_modified_by
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.last_modified_date
     *
     * @mbg.generated
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   バージョン(排他制御用)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   従業員ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.emp_id
     *
     * @mbg.generated
     */
    private String empId;

    /**
     * Database Column Remarks:
     *   従業員氏名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.emp_name
     *
     * @mbg.generated
     */
    private String empName;

    /**
     * Database Column Remarks:
     *   所属部署
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.organization_id
     *
     * @mbg.generated
     */
    private String organizationId;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   役職
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.position_id
     *
     * @mbg.generated
     */
    private String positionId;

    /**
     * Database Column Remarks:
     *   ステータス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.employee.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms.employee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}